name: Update cpanfile.snapshot
on:
  schedule:
    - cron: "1 15 * * 0"
  workflow_dispatch:
jobs:
  update-dep:
    runs-on: "ubuntu-22.04"
    container:
      image: perl:5.22-buster
    steps:
      - name: Generate Auth Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: haarg/setup-git-user@v1
        with:
          app: ${{ steps.app-token.output.app-slug }}
      - uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Update cpanfile.snapshot
        uses: metacpan/metacpan-actions/update-snapshot@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Update cpanfile.snapshot
          title: Update cpanfile.snapshot
          sign-commits: true
          body: |
            [GitHub Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          branch: update-cpanfile-snapshot
